### ISSUE TITLE
[Bug] author-in-team isn't labeling when author is a member of the specified team

### ISSUE THREAD

**Issue by swrobel** [srvaroa/labeler#153]
I have tested this in our repo, and believe I have an explanation of why this isn't working:

The [go github function](https://github.com/srvaroa/labeler/pull/150/files#diff-329f84be6a6b359043a3791d6d77cba74f98a673ff4ce35421b8234d90ed00e0R248) that is called, [GetOrgMembership](https://pkg.go.dev/github.com/google/go-github/v50/github#OrganizationsService.GetOrgMembership), uses the ["Get organization membership for a user"](https://docs.github.com/en/rest/orgs/members?apiVersion=2022-11-28#get-organization-membership-for-a-user) endpoint, which doesn't seem to contain any info about the teams within that org that the user is a member of. Also, we are passing a `team` string to the second argument, which expects an `org` string instead, leading to 404s always being returned in the logs from the action:

```
[Author is member of team] skip, GET https://api.github.com/orgs/{team}/memberships/{user}: 404 Not Found []
```

I think instead, you may need to use the [GetTeamMembershipBySlug](https://pkg.go.dev/github.com/google/go-github/v50/github#TeamsService.GetTeamMembershipBySlug) function, which requires:
1. org identifier (perhaps this is already available somewhere for other API calls that are already being made by labeler? Otherwise, it will probably have to be added to config)
2. team _slug_, as opposed to the team name (as [currently documented](https://github.com/srvaroa/labeler/pull/150/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R351)), which can contain spaces
3. user (we already have this)

**Comment by srvaroa** [comment]
Many thanks for the report and triage. I will fix this in the next few days.

**Comment by srvaroa** [comment]
I have just released this, it should be available in the latest release.

I don't have an actual org + teams to test this with, but do let me know if the behaviour works.

Thanks again for the diagnose.

**Comment by swrobel** [comment]
Someone else opened an issue, but I added my findings here as this still isn't working for me (sorry, haven't had a chance to test until now) https://github.com/srvaroa/labeler/issues/160#issuecomment-2499269469
